export const USER_UPDATE_AVATAR = 'USER_UPDATE_AVATAR';
export const USER_UPDATE_USERNAME = 'USER_UPDATE_USERNAME';
export const USER_UPDATE_FULLNAME = 'USER_UPDATE_FULLNAME';
export const USER_UPDATE_GENDER = 'USER_UPDATE_GENDER';
export const USER_UPDATE_DEFAULT_COUNTRY = 'USER_UPDATE_DEFAULT_COUNTRY';
