export const CHANGE_CENTER_LOCATION = 'App/CHANGE_CENTER_LOCATION';
export const CHANGE_ZOOM_LEVEL = 'App/CHANGE_ZOOM_LEVEL';

export const SYNCHRONIZE_LAT_LON = 'Parkings Page/SYNCHRONIZE_LAT_LON';
export const ASK_PERMISSION_FOR_GEO_LOCATION = 'Parkings Page/ASK_PERMISSION_FOR_GEO_LOCATION';

export const PARKINGS_FETCH_START = 'Parkings Page/PARKINGS_FETCH_START';
export const PARKINGS_REQUEST_FOR_FETCH = 'Parkings Page/PARKINGS_REQUEST_FOR_FETCH';
export const PARKINGS_FETCH_SUCCESS = 'Parkings Page/PARKINGS_FETCH_SUCCESS';

export const POST_PARKING_ATTEMPT = 'Parkings Page/POST_PARKING_ATTEMPT';
export const POST_PARKING_SUCCESS = 'Parkings Page/POST_PARKING_SUCCESS';
export const POST_PARKING_ERROR = 'Parkings Page/POST_PARKING_ERROR';

export const REMOVE_PARKING = 'Parkings Page/REMOVE_PARKING';
export const SET_PARKING_FREE_STATUS = 'Parkings Page/SET_PARKING_FREE_STATUS';

export const CHECK_PARKOPEDIA_UPDATES_REQUEST = 'Parkings Page/CHECK_PARKOPEDIA_UPDATES_REQUEST';
export const CHECK_PARKOPEDIA_UPDATES_SUCCESS = 'Parkings Page/CHECK_PARKOPEDIA_UPDATES_SUCCESS';

export const CLEAR_ALL_FREE_SLOTS = 'Parkings Page/CLEAR_ALL_FREE_SLOTS';
export const CLEAR_VISIBLE_FREE_SLOTS = 'Parkings Page/CLEAR_VISIBLE_FREE_SLOTS';
