export const CHANGE_CENTER_LOCATION = 'App/CHANGE_CENTER_LOCATION';
export const CHANGE_ZOOM_LEVEL = 'App/CHANGE_ZOOM_LEVEL';

export const SYNCHRONIZE_LAT_LON = 'Parkings Page/SYNCHRONIZE_LAT_LON';

export const PARKINGS_FETCH_START = 'Parkings Page/PARKINGS_FETCH_START';
export const PARKINGS_REQUEST_FOR_FETCH = 'Parkings Page/PARKINGS_REQUEST_FOR_FETCH';
export const PARKINGS_FETCH_SUCCESS = 'Parkings Page/PARKINGS_FETCH_SUCCESS';

export const CHECK_PARKOPEDIA_UPDATES_REQUEST = 'Parkings Page/CHECK_PARKOPEDIA_UPDATES_REQUEST';
export const CHECK_PARKOPEDIA_UPDATES_SUCCESS = 'Parkings Page/CHECK_PARKOPEDIA_UPDATES_SUCCESS';

export const CLEAR_FREE_SLOTS = 'Parkings Page/CLEAR_FREE_SLOTS';
