export const CHANGE_CENTER_LOCATION = 'App/CHANGE_CENTER_LOCATION';

export const SYNCHRONIZE_LAT_LON = 'Parkings Page/SYNCHRONIZE_LAT_LON';

export const PARKINGS_FETCH_START = 'Parkings Page/PARKINGS_FETCH_START';
export const PARKINGS_FETCH_SUCCESS = 'Parkings Page/PARKINGS_FETCH_SUCCESS';
