export const CHANGE_CENTER_LOCATION = 'App/CHANGE_CENTER_LOCATION';

export const PARKINGS_FETCH_START = 'Parkings Page/PARKINGS_FETCH_START';
export const PARKINGS_FETCH_SUCCESS = 'Parkings Page/PARKINGS_FETCH_SUCCESS';
