interface colorsPalette {
  readonly colorMainText: string,
  readonly greenParking: string,
  readonly colorGreyPopup: string,
  readonly colorAntiMain: string,
  readonly colorExtraText: string,
  readonly colorAccent1: string,
  readonly colorAccent2: string,
  readonly colorAccent3: string,
  readonly colorAccent4: string,
  readonly colorRouteInactive: string,
  readonly colorBorder: string,
  readonly colorBorderError: string,
  readonly pageBackground: string,
}

export const COLORS: colorsPalette = {
  colorMainText: '#333333',
  greenParking: '#68ce55',
  colorGreyPopup: '#d2d2d2',
  colorAntiMain: '#ffffff',
  colorExtraText: '#757575',
  colorAccent1: '#7ceb7e',
  colorAccent2: '#ff4a4a',
  colorAccent3: '#f1970f',
  colorAccent4: '#29a1fb',
  colorRouteInactive: '#b6b6b6',
  colorBorder: '#dee1e4',
  colorBorderError: '#df4930',
  pageBackground: '#f5f6fa',
};
