export const LOAD_CAR_PARAMETERS_ATTEMPT = 'LOAD_CAR_PARAMETERS_ATTEMPT';
export const LOAD_CAR_PARAMETERS_SUCCESS = 'LOAD_CAR_PARAMETERS_SUCCESS';
export const LOAD_CAR_PARAMETERS_ERROR = 'LOAD_CAR_PARAMETERS_ERROR';
export const LOAD_CAR_PARAMETERS_RESET = 'LOAD_CAR_PARAMETERS_RESET';

export const UPDATE_CAR_PARAMETER_VALUE_ATTEMPT = 'UPDATE_CAR_PARAMETER_VALUE_ATTEMPT';
export const UPDATE_CAR_PARAMETER_VALUE_SUCCESS = 'UPDATE_CAR_PARAMETER_VALUE_SUCCESS';
export const UPDATE_CAR_PARAMETER_VALUE_ERROR = 'UPDATE_CAR_PARAMETER_VALUE_ERROR';

export const LOAD_CAR_MANUFACTURERS_ATTEMPT = 'LOAD_CAR_MANUFACTURERS_ATTEMPT';
export const LOAD_CAR_MANUFACTURERS_SUCCESS = 'LOAD_CAR_MANUFACTURERS_SUCCESS';
export const LOAD_CAR_MANUFACTURERS_ERROR = 'LOAD_CAR_MANUFACTURERS_ERROR';
