export const INIT_USER_INFO_ON_LOAD = 'INIT_USER_INFO_ON_LOAD';
export const NOT_ALLOWED_WITH_GUEST_PERMISSION = 'NOT_ALLOWED_WITH_GUEST_PERMISSION';

export const USER_SIGN_IN_ATTEMPT = 'USER_SIGN_IN_ATTEMPT';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_ERROR = 'USER_SIGN_IN_ERROR';

export const USER_SIGN_OUT_ATTEMPT = 'USER_SIGN_OUT_ATTEMPT';
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS';
export const USER_SIGN_OUT_ERROR = 'USER_SIGN_OUT_ERROR';

export const USER_SIGN_UP_ATTEMPT = 'USER_SIGN_UP_ATTEMPT';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_ERROR = 'USER_SIGN_UP_ERROR';

export const USER_UPDATE_AVATAR = 'USER_UPDATE_AVATAR';
export const USER_UPDATE_USERNAME = 'USER_UPDATE_USERNAME';
export const USER_UPDATE_FULLNAME = 'USER_UPDATE_FULLNAME';
export const USER_UPDATE_GENDER = 'USER_UPDATE_GENDER';
export const USER_UPDATE_DEFAULT_COUNTRY = 'USER_UPDATE_DEFAULT_COUNTRY';
