export const INIT_USER_INFO_ON_LOAD = 'INIT_USER_INFO_ON_LOAD';
export const NOT_ALLOWED_WITH_GUEST_PERMISSION = 'NOT_ALLOWED_WITH_GUEST_PERMISSION';

export const USER_SIGN_IN_ATTEMPT = 'USER_SIGN_IN_ATTEMPT';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_ERROR = 'USER_SIGN_IN_ERROR';

export const USER_SIGN_OUT_ATTEMPT = 'USER_SIGN_OUT_ATTEMPT';
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS';
export const USER_SIGN_OUT_ERROR = 'USER_SIGN_OUT_ERROR';
