export const SET_VOICE_NOTIFICATIONS = 'SET_VOICE_NOTIFICATIONS';

export const START_CHECKING_PARKING_UPDATES = 'Parkings Page/START_CHECKING_PARKING_UPDATES';
export const STOP_CHECKING_PARKING_UPDATES = 'Parkings Page/STOP_CHECKING_PARKING_UPDATES';
export const SET_CHECKING_PARKING_UPDATES = 'Parkings Page/SET_CHECKING_PARKING_UPDATES';
